//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/NPC/NPCInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NPCInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NPCInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NPCInputActions"",
    ""maps"": [
        {
            ""name"": ""NPC"",
            ""id"": ""edb4ccd4-1e7e-4759-8114-c69dfadb8338"",
            ""actions"": [
                {
                    ""name"": ""OpenDialog"",
                    ""type"": ""Button"",
                    ""id"": ""89393ec4-6398-4fa5-b6b8-4302d8bfac85"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6f65562a-ca6f-452f-8b92-ecc5db88ef51"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // NPC
        m_NPC = asset.FindActionMap("NPC", throwIfNotFound: true);
        m_NPC_OpenDialog = m_NPC.FindAction("OpenDialog", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // NPC
    private readonly InputActionMap m_NPC;
    private INPCActions m_NPCActionsCallbackInterface;
    private readonly InputAction m_NPC_OpenDialog;
    public struct NPCActions
    {
        private @NPCInputActions m_Wrapper;
        public NPCActions(@NPCInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenDialog => m_Wrapper.m_NPC_OpenDialog;
        public InputActionMap Get() { return m_Wrapper.m_NPC; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NPCActions set) { return set.Get(); }
        public void SetCallbacks(INPCActions instance)
        {
            if (m_Wrapper.m_NPCActionsCallbackInterface != null)
            {
                @OpenDialog.started -= m_Wrapper.m_NPCActionsCallbackInterface.OnOpenDialog;
                @OpenDialog.performed -= m_Wrapper.m_NPCActionsCallbackInterface.OnOpenDialog;
                @OpenDialog.canceled -= m_Wrapper.m_NPCActionsCallbackInterface.OnOpenDialog;
            }
            m_Wrapper.m_NPCActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OpenDialog.started += instance.OnOpenDialog;
                @OpenDialog.performed += instance.OnOpenDialog;
                @OpenDialog.canceled += instance.OnOpenDialog;
            }
        }
    }
    public NPCActions @NPC => new NPCActions(this);
    public interface INPCActions
    {
        void OnOpenDialog(InputAction.CallbackContext context);
    }
}
